layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/e72db8b119f1994a0a9fff591acb4d257447ba85/topics/kubernetes/kubernetes.png

  - name: Deployment
    web_url: https://github.com/topics/deployment
    image_url: https://raw.githubusercontent.com/github/explore/e72db8b119f1994a0a9fff591acb4d257447ba85/topics/deployment/deployment.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/e72db8b119f1994a0a9fff591acb4d257447ba85/topics/linux/linux.png
